### ISSUE TITLE
If `Task Check Frequency` is set to 1 then `Messages until next AI task completion check` ends up reaching -1 which seems like a bug.

### ISSUE THREAD

**Issue by left1000** [SillyTavern/Extension-Objective#10]
If `Task Check Frequency` is set to 1 then `Messages until next AI task completion check` ends up reaching -1 which seems like a bug.

It works properly if task check is 2 or higher.

**Comment by left1000** [comment]
Nevermind, not sure how or why, but this issue went away, I must've been doing something else that effected it negatively, maybe swipes are what caused it?

**Comment by left1000** [comment]
My new guess is that this is caused by a bug that occurs when you click continue in ST as it must not reset the messages until counter, but it does reduce it to -1 instead of leaving it at some other number...

Assuming my guess is right, the messages until complete counter doesn't interact well with continue.

**Comment by Cohee1207** [comment]
Try pulling the extension update and check again please. Continues are now skipped from the checks.

**Comment by left1000** [comment]
Yes it is fixed now thanks!
